### ISSUE TITLE
Namens Autovervollständigung für Nachrichten und TH

### ISSUE THREAD

**Issue by swalesch** [Pandastan/Evergore#5]

**Comment by swalesch** [comment]
Es fehlt noch der Lokal storage um traffic/serverlast zu reduzieren und die readme muss noch angepasst werden

**Comment by swalesch** [comment]
ein update des lokal storage fehlt noch @Pandastan, schreibste das noch?

**Comment by Pandastan** [comment]
Grad commited. Hoffe es funktioniert so wie gedacht. Falls Bugs auftreten, bitte hier melden.
